server:
  port: 8002
spring:
  apllcation:
    name: goods-service

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        service: goods-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sqc?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=GMT
    username: root
    password: root
#    sentinel:
#      transport:
#        dashboard: localhost:8021
#feign:
#  sentinel:
#    enabled: true