server:
  port: 8003
spring:
  apllcation:
    name: manage-server
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        service: manage-server
#  redis:
#    host: localhost
#    port: 6379
#    database: 0
#    password:
#    timeout: 10000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sqc?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: root
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#    publisher-confirm-type: correlated
#    # 确认消息已发送到队列(Queue)
#    publisher-returns: true
jetcache:
  statIntervalMinutes: 1
  areaInCacheName: false
  hiddenPackages: cn.su #隐藏包名
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
      # expireAfterWriteInMillis: 100000 # 失效的时间 毫秒
  remote:
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: localhost
      port: 6379
logging:
  level:
    cn.su: debug
  file:
    path: logs
    max-size: 521MB

#  path: logs/
#  file:
#    max-size: 1GB
#    sentinel:
#      transport:
#        dashboard: localhost:8021
#feign:
#  sentinel:
#    enabled: true