server:
  port: 8082
spring:
  apllcation:
    name: stock-server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.17.51:8848
        service: stock-server
logging:
  level:
    sqc: debug
  file:
    path: logs
    max-size: 521MB