server:
  port: 8002
spring:
  apllcation:
    name: goods-server
#  redis:
#    host: localhost
#    port: 6379
#    database: 0
#    password:
#    timeout: 10000
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        service: good-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sqc?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=GMT&allowPublicKeyRetrieval=true
    username: root
    password: root
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#    publisher-confirm-type: correlated
#    #确认消息已发送到队列(Queue)
#    publisher-returns: true

logging:
  level:
    sqc.goods.dao: debug

#  path: logs/
#  file:
#    max-size: 1GB
#    sentinel:
#      transport:
#        dashboard: localhost:8021
#feign:
#  sentinel:
#    enabled: true