server:
  port: 10000
spring:
  apllcation:
    name: schedule-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        service: schedule-service
    sentinel:
      transport:
        dashboard: localhost：8021
