server:
  port: 10000
spring:
  apllcation:
    name: schedule-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/scheduler?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        service: schedule-service
    sentinel:
      transport:
        dashboard: localhost：8021
